module NotMain where
-- generated by higher-level SC from eWiseAddChain.hs

data QTree a = QNone  | QVal a | QNode (QTree a) (QTree a) (QTree a) (QTree a) | QError deriving Show;
data MaskQTree  = MNone  | MVal  | MNode MaskQTree MaskQTree MaskQTree MaskQTree;

pls = (+)

m1 = QNode (QNode (QNode (QVal 1) QNone QNone (QVal 2)) QNone QNone (QNode (QVal 3) QNone QNone (QVal 4))) QNone QNone (QNode (QNode (QVal 5) QNone QNone (QVal 6)) QNone 
     QNone (QNode (QVal 7) QNone QNone (QVal 8)))

m2 = m1

m3 = m1

main = do 
  let
   f=(\x->
    (\y->
      (\z->
        case  x  of {
          QError  -> QError;
          QNone  ->
            case  y  of {
              QError  -> QError;
              QNone  ->
                case  z  of {
                  QError  -> QError;
                  QNone  -> QNone;
                  QVal x5623 -> (QVal x5623);
                  QNode x5624 x5625 x5626 x5627 -> (QNode x5624 x5625 x5626 x5627);
                };
              QVal x5598 ->
                case  z  of {
                  QError  -> QError;
                  QNone  -> (QVal x5598);
                  QVal x5633 -> (QVal ((pls x5598) x5633));
                  QNode x5634 x5635 x5636 x5637 -> QError;
                };
              QNode x5604 x5605 x5606 x5607 ->
                case  z  of {
                  QError  -> QError;
                  QNone  -> (QNode x5604 x5605 x5606 x5607);
                  QVal x5643 -> QError;
                  QNode x5644 x5645 x5646 x5647 ->
                    (QNode
                      (let
                        g=(\u->
                          (\v->
                            case  u  of {
                              QError  -> QError;
                              QNone  ->
                                case  v  of {
                                  QError  -> QError;
                                  QNone  -> QNone;
                                  QVal x7576 -> (QVal x7576);
                                  QNode x7577 x7578 x7579 x7580 -> (QNode x7577 x7578 x7579 x7580);
                                };
                              QVal x7561 ->
                                case  v  of {
                                  QError  -> QError;
                                  QNone  -> (QVal x7561);
                                  QVal x7581 -> (QVal ((pls x7561) x7581));
                                  QNode x7582 x7583 x7584 x7585 -> QError;
                                };
                              QNode x7567 x7568 x7569 x7570 ->
                                case  v  of {
                                  QError  -> QError;
                                  QNone  -> (QNode x7567 x7568 x7569 x7570);
                                  QVal x7586 -> QError;
                                  QNode x7587 x7588 x7589 x7590 ->
                                    (QNode ((g x7567) x7587) ((g x7568) x7588) ((g x7569) x7589) ((g x7570) x7590));
                                };
                            }))
                      in
                        ((g x5604) x5644))
                      (let
                        h=(\w->
                          (\p->
                            case  w  of {
                              QError  -> QError;
                              QNone  ->
                                case  p  of {
                                  QError  -> QError;
                                  QNone  -> QNone;
                                  QVal x7016 -> (QVal x7016);
                                  QNode x7017 x7018 x7019 x7020 -> (QNode x7017 x7018 x7019 x7020);
                                };
                              QVal x7001 ->
                                case  p  of {
                                  QError  -> QError;
                                  QNone  -> (QVal x7001);
                                  QVal x7021 -> (QVal ((pls x7001) x7021));
                                  QNode x7022 x7023 x7024 x7025 -> QError;
                                };
                              QNode x7007 x7008 x7009 x7010 ->
                                case  p  of {
                                  QError  -> QError;
                                  QNone  -> (QNode x7007 x7008 x7009 x7010);
                                  QVal x7026 -> QError;
                                  QNode x7027 x7028 x7029 x7030 ->
                                    (QNode ((h x7007) x7027) ((h x7008) x7028) ((h x7009) x7029) ((h x7010) x7030));
                                };
                            }))
                      in
                        ((h x5605) x5645))
                      (let
                        f1=(\r->
                          (\s->
                            case  r  of {
                              QError  -> QError;
                              QNone  ->
                                case  s  of {
                                  QError  -> QError;
                                  QNone  -> QNone;
                                  QVal x6456 -> (QVal x6456);
                                  QNode x6457 x6458 x6459 x6460 -> (QNode x6457 x6458 x6459 x6460);
                                };
                              QVal x6441 ->
                                case  s  of {
                                  QError  -> QError;
                                  QNone  -> (QVal x6441);
                                  QVal x6461 -> (QVal ((pls x6441) x6461));
                                  QNode x6462 x6463 x6464 x6465 -> QError;
                                };
                              QNode x6447 x6448 x6449 x6450 ->
                                case  s  of {
                                  QError  -> QError;
                                  QNone  -> (QNode x6447 x6448 x6449 x6450);
                                  QVal x6466 -> QError;
                                  QNode x6467 x6468 x6469 x6470 ->
                                    (QNode ((f1 x6447) x6467) ((f1 x6448) x6468) ((f1 x6449) x6469) ((f1 x6450) x6470));
                                };
                            }))
                      in
                        ((f1 x5606) x5646))
                      (let
                        g1=(\t->
                          (\x1->
                            case  t  of {
                              QError  -> QError;
                              QNone  ->
                                case  x1  of {
                                  QError  -> QError;
                                  QNone  -> QNone;
                                  QVal x5896 -> (QVal x5896);
                                  QNode x5897 x5898 x5899 x5900 -> (QNode x5897 x5898 x5899 x5900);
                                };
                              QVal x5881 ->
                                case  x1  of {
                                  QError  -> QError;
                                  QNone  -> (QVal x5881);
                                  QVal x5901 -> (QVal ((pls x5881) x5901));
                                  QNode x5902 x5903 x5904 x5905 -> QError;
                                };
                              QNode x5887 x5888 x5889 x5890 ->
                                case  x1  of {
                                  QError  -> QError;
                                  QNone  -> (QNode x5887 x5888 x5889 x5890);
                                  QVal x5906 -> QError;
                                  QNode x5907 x5908 x5909 x5910 ->
                                    (QNode ((g1 x5887) x5907) ((g1 x5888) x5908) ((g1 x5889) x5909) ((g1 x5890) x5910));
                                };
                            }))
                      in
                        ((g1 x5607) x5647)));
                };
            };
          QVal x95 ->
            case  y  of {
              QError  -> QError;
              QNone  ->
                case  z  of {
                  QError  -> QError;
                  QNone  -> (QVal x95);
                  QVal x5399 -> (QVal ((pls x95) x5399));
                  QNode x5400 x5401 x5402 x5403 -> QError;
                };
              QVal x5374 ->
                case  z  of {
                  QError  -> QError;
                  QNone  -> (QVal ((pls x95) x5374));
                  QVal x5409 -> (QVal ((pls x95) ((pls x5374) x5409)));
                  QNode x5410 x5411 x5412 x5413 -> QError;
                };
              QNode x5380 x5381 x5382 x5383 ->
                case  z  of {
                  QError  -> QError;
                  QNone  -> QError;
                  QVal x5419 -> QError;
                  QNode x5420 x5421 x5422 x5423 -> QError;
                };
            };
          QNode x101 x102 x103 x104 ->
            case  y  of {
              QError  -> QError;
              QNone  ->
                case  z  of {
                  QError  -> QError;
                  QNone  -> (QNode x101 x102 x103 x104);
                  QVal x259 -> QError;
                  QNode x260 x261 x262 x263 ->
                    (QNode
                      (let
                        h1=(\y1->
                          (\z1->
                            case  y1  of {
                              QError  -> QError;
                              QNone  ->
                                case  z1  of {
                                  QError  -> QError;
                                  QNone  -> QNone;
                                  QVal x4814 -> (QVal x4814);
                                  QNode x4815 x4816 x4817 x4818 -> (QNode x4815 x4816 x4817 x4818);
                                };
                              QVal x4799 ->
                                case  z1  of {
                                  QError  -> QError;
                                  QNone  -> (QVal x4799);
                                  QVal x4819 -> (QVal ((pls x4799) x4819));
                                  QNode x4820 x4821 x4822 x4823 -> QError;
                                };
                              QNode x4805 x4806 x4807 x4808 ->
                                case  z1  of {
                                  QError  -> QError;
                                  QNone  -> (QNode x4805 x4806 x4807 x4808);
                                  QVal x4824 -> QError;
                                  QNode x4825 x4826 x4827 x4828 ->
                                    (QNode ((h1 x4805) x4825) ((h1 x4806) x4826) ((h1 x4807) x4827) ((h1 x4808) x4828));
                                };
                            }))
                      in
                        ((h1 x101) x260))
                      (let
                        f2=(\u1->
                          (\v1->
                            case  u1  of {
                              QError  -> QError;
                              QNone  ->
                                case  v1  of {
                                  QError  -> QError;
                                  QNone  -> QNone;
                                  QVal x4254 -> (QVal x4254);
                                  QNode x4255 x4256 x4257 x4258 -> (QNode x4255 x4256 x4257 x4258);
                                };
                              QVal x4239 ->
                                case  v1  of {
                                  QError  -> QError;
                                  QNone  -> (QVal x4239);
                                  QVal x4259 -> (QVal ((pls x4239) x4259));
                                  QNode x4260 x4261 x4262 x4263 -> QError;
                                };
                              QNode x4245 x4246 x4247 x4248 ->
                                case  v1  of {
                                  QError  -> QError;
                                  QNone  -> (QNode x4245 x4246 x4247 x4248);
                                  QVal x4264 -> QError;
                                  QNode x4265 x4266 x4267 x4268 ->
                                    (QNode ((f2 x4245) x4265) ((f2 x4246) x4266) ((f2 x4247) x4267) ((f2 x4248) x4268));
                                };
                            }))
                      in
                        ((f2 x102) x261))
                      (let
                        g2=(\w1->
                          (\p1->
                            case  w1  of {
                              QError  -> QError;
                              QNone  ->
                                case  p1  of {
                                  QError  -> QError;
                                  QNone  -> QNone;
                                  QVal x3694 -> (QVal x3694);
                                  QNode x3695 x3696 x3697 x3698 -> (QNode x3695 x3696 x3697 x3698);
                                };
                              QVal x3679 ->
                                case  p1  of {
                                  QError  -> QError;
                                  QNone  -> (QVal x3679);
                                  QVal x3699 -> (QVal ((pls x3679) x3699));
                                  QNode x3700 x3701 x3702 x3703 -> QError;
                                };
                              QNode x3685 x3686 x3687 x3688 ->
                                case  p1  of {
                                  QError  -> QError;
                                  QNone  -> (QNode x3685 x3686 x3687 x3688);
                                  QVal x3704 -> QError;
                                  QNode x3705 x3706 x3707 x3708 ->
                                    (QNode ((g2 x3685) x3705) ((g2 x3686) x3706) ((g2 x3687) x3707) ((g2 x3688) x3708));
                                };
                            }))
                      in
                        ((g2 x103) x262))
                      (let
                        h2=(\r1->
                          (\s1->
                            case  r1  of {
                              QError  -> QError;
                              QNone  ->
                                case  s1  of {
                                  QError  -> QError;
                                  QNone  -> QNone;
                                  QVal x3134 -> (QVal x3134);
                                  QNode x3135 x3136 x3137 x3138 -> (QNode x3135 x3136 x3137 x3138);
                                };
                              QVal x3119 ->
                                case  s1  of {
                                  QError  -> QError;
                                  QNone  -> (QVal x3119);
                                  QVal x3139 -> (QVal ((pls x3119) x3139));
                                  QNode x3140 x3141 x3142 x3143 -> QError;
                                };
                              QNode x3125 x3126 x3127 x3128 ->
                                case  s1  of {
                                  QError  -> QError;
                                  QNone  -> (QNode x3125 x3126 x3127 x3128);
                                  QVal x3144 -> QError;
                                  QNode x3145 x3146 x3147 x3148 ->
                                    (QNode ((h2 x3125) x3145) ((h2 x3126) x3146) ((h2 x3127) x3147) ((h2 x3128) x3148));
                                };
                            }))
                      in
                        ((h2 x104) x263)));
                };
              QVal x234 ->
                case  z  of {
                  QError  -> QError;
                  QNone  -> QError;
                  QVal x269 -> QError;
                  QNode x270 x271 x272 x273 -> QError;
                };
              QNode x240 x241 x242 x243 ->
                case  z  of {
                  QError  -> QError;
                  QNone  ->
                    (QNode
                      (let
                        f3=(\t1->
                          (\x2->
                            case  t1  of {
                              QError  -> QError;
                              QNone  ->
                                case  x2  of {
                                  QError  -> QError;
                                  QNone  -> QNone;
                                  QVal x2534 -> (QVal x2534);
                                  QNode x2535 x2536 x2537 x2538 -> (QNode x2535 x2536 x2537 x2538);
                                };
                              QVal x2519 ->
                                case  x2  of {
                                  QError  -> QError;
                                  QNone  -> (QVal x2519);
                                  QVal x2539 -> (QVal ((pls x2519) x2539));
                                  QNode x2540 x2541 x2542 x2543 -> QError;
                                };
                              QNode x2525 x2526 x2527 x2528 ->
                                case  x2  of {
                                  QError  -> QError;
                                  QNone  -> (QNode x2525 x2526 x2527 x2528);
                                  QVal x2544 -> QError;
                                  QNode x2545 x2546 x2547 x2548 ->
                                    (QNode ((f3 x2525) x2545) ((f3 x2526) x2546) ((f3 x2527) x2547) ((f3 x2528) x2548));
                                };
                            }))
                      in
                        ((f3 x101) x240))
                      (let
                        g3=(\y2->
                          (\z2->
                            case  y2  of {
                              QError  -> QError;
                              QNone  ->
                                case  z2  of {
                                  QError  -> QError;
                                  QNone  -> QNone;
                                  QVal x1974 -> (QVal x1974);
                                  QNode x1975 x1976 x1977 x1978 -> (QNode x1975 x1976 x1977 x1978);
                                };
                              QVal x1959 ->
                                case  z2  of {
                                  QError  -> QError;
                                  QNone  -> (QVal x1959);
                                  QVal x1979 -> (QVal ((pls x1959) x1979));
                                  QNode x1980 x1981 x1982 x1983 -> QError;
                                };
                              QNode x1965 x1966 x1967 x1968 ->
                                case  z2  of {
                                  QError  -> QError;
                                  QNone  -> (QNode x1965 x1966 x1967 x1968);
                                  QVal x1984 -> QError;
                                  QNode x1985 x1986 x1987 x1988 ->
                                    (QNode ((g3 x1965) x1985) ((g3 x1966) x1986) ((g3 x1967) x1987) ((g3 x1968) x1988));
                                };
                            }))
                      in
                        ((g3 x102) x241))
                      (let
                        h3=(\u2->
                          (\v2->
                            case  u2  of {
                              QError  -> QError;
                              QNone  ->
                                case  v2  of {
                                  QError  -> QError;
                                  QNone  -> QNone;
                                  QVal x1414 -> (QVal x1414);
                                  QNode x1415 x1416 x1417 x1418 -> (QNode x1415 x1416 x1417 x1418);
                                };
                              QVal x1399 ->
                                case  v2  of {
                                  QError  -> QError;
                                  QNone  -> (QVal x1399);
                                  QVal x1419 -> (QVal ((pls x1399) x1419));
                                  QNode x1420 x1421 x1422 x1423 -> QError;
                                };
                              QNode x1405 x1406 x1407 x1408 ->
                                case  v2  of {
                                  QError  -> QError;
                                  QNone  -> (QNode x1405 x1406 x1407 x1408);
                                  QVal x1424 -> QError;
                                  QNode x1425 x1426 x1427 x1428 ->
                                    (QNode ((h3 x1405) x1425) ((h3 x1406) x1426) ((h3 x1407) x1427) ((h3 x1408) x1428));
                                };
                            }))
                      in
                        ((h3 x103) x242))
                      (let
                        f4=(\w2->
                          (\p2->
                            case  w2  of {
                              QError  -> QError;
                              QNone  ->
                                case  p2  of {
                                  QError  -> QError;
                                  QNone  -> QNone;
                                  QVal x854 -> (QVal x854);
                                  QNode x855 x856 x857 x858 -> (QNode x855 x856 x857 x858);
                                };
                              QVal x839 ->
                                case  p2  of {
                                  QError  -> QError;
                                  QNone  -> (QVal x839);
                                  QVal x859 -> (QVal ((pls x839) x859));
                                  QNode x860 x861 x862 x863 -> QError;
                                };
                              QNode x845 x846 x847 x848 ->
                                case  p2  of {
                                  QError  -> QError;
                                  QNone  -> (QNode x845 x846 x847 x848);
                                  QVal x864 -> QError;
                                  QNode x865 x866 x867 x868 ->
                                    (QNode ((f4 x845) x865) ((f4 x846) x866) ((f4 x847) x867) ((f4 x848) x868));
                                };
                            }))
                      in
                        ((f4 x104) x243)));
                  QVal x279 -> QError;
                  QNode x280 x281 x282 x283 ->
                    (QNode (((f x101) x240) x280) (((f x102) x241) x281) (((f x103) x242) x282) (((f x104) x243) x283));
                };
            };
        })))
  
  print (((f m1) m2) m3)
