-- generated by higher-level SC from eWiseAddChain.hs

data QTree a = QNone  | QVal a | QNode (QTree a) (QTree a) (QTree a) (QTree a) | QError ;
data MaskQTree  = MNone  | MVal  | MNode MaskQTree MaskQTree MaskQTree MaskQTree;

pls = (+)

mlt = (*)



(letrec
  f=(\x->
    (\y->
      (\z->
        case  x  of {
          QError  -> QError;
          QNone  ->
            case  y  of {
              QError  -> QError;
              QNone  ->
                case  z  of {
                  QError  -> QError;
                  QNone  -> QNone;
                  QVal $1143 -> QNone;
                  QNode $1144 $1145 $1146 $1147 -> QNone;
                };
              QVal $1118 ->
                case  z  of {
                  QError  -> QError;
                  QNone  -> QNone;
                  QVal $1153 -> (QVal ((mlt $1118) $1153));
                  QNode $1154 $1155 $1156 $1157 -> QError;
                };
              QNode $1124 $1125 $1126 $1127 ->
                case  z  of {
                  QError  -> QError;
                  QNone  -> QNone;
                  QVal $1163 -> QError;
                  QNode $1164 $1165 $1166 $1167 ->
                    (QNode
                      (letrec
                        g=(\u->
                          (\v->
                            case  u  of {
                              QError  -> QError;
                              QNone  ->
                                case  v  of {
                                  QError  -> QError;
                                  QNone  -> QNone;
                                  QVal $3096 -> QNone;
                                  QNode $3097 $3098 $3099 $3100 -> QNone;
                                };
                              QVal $3081 ->
                                case  v  of {
                                  QError  -> QError;
                                  QNone  -> QNone;
                                  QVal $3101 -> (QVal ((mlt $3081) $3101));
                                  QNode $3102 $3103 $3104 $3105 -> QError;
                                };
                              QNode $3087 $3088 $3089 $3090 ->
                                case  v  of {
                                  QError  -> QError;
                                  QNone  -> QNone;
                                  QVal $3106 -> QError;
                                  QNode $3107 $3108 $3109 $3110 ->
                                    (QNode ((g $3087) $3107) ((g $3088) $3108) ((g $3089) $3109) ((g $3090) $3110));
                                };
                            }))
                      in
                        ((g $1124) $1164))
                      (letrec
                        h=(\w->
                          (\p->
                            case  w  of {
                              QError  -> QError;
                              QNone  ->
                                case  p  of {
                                  QError  -> QError;
                                  QNone  -> QNone;
                                  QVal $2536 -> QNone;
                                  QNode $2537 $2538 $2539 $2540 -> QNone;
                                };
                              QVal $2521 ->
                                case  p  of {
                                  QError  -> QError;
                                  QNone  -> QNone;
                                  QVal $2541 -> (QVal ((mlt $2521) $2541));
                                  QNode $2542 $2543 $2544 $2545 -> QError;
                                };
                              QNode $2527 $2528 $2529 $2530 ->
                                case  p  of {
                                  QError  -> QError;
                                  QNone  -> QNone;
                                  QVal $2546 -> QError;
                                  QNode $2547 $2548 $2549 $2550 ->
                                    (QNode ((h $2527) $2547) ((h $2528) $2548) ((h $2529) $2549) ((h $2530) $2550));
                                };
                            }))
                      in
                        ((h $1125) $1165))
                      (letrec
                        f1=(\r->
                          (\s->
                            case  r  of {
                              QError  -> QError;
                              QNone  ->
                                case  s  of {
                                  QError  -> QError;
                                  QNone  -> QNone;
                                  QVal $1976 -> QNone;
                                  QNode $1977 $1978 $1979 $1980 -> QNone;
                                };
                              QVal $1961 ->
                                case  s  of {
                                  QError  -> QError;
                                  QNone  -> QNone;
                                  QVal $1981 -> (QVal ((mlt $1961) $1981));
                                  QNode $1982 $1983 $1984 $1985 -> QError;
                                };
                              QNode $1967 $1968 $1969 $1970 ->
                                case  s  of {
                                  QError  -> QError;
                                  QNone  -> QNone;
                                  QVal $1986 -> QError;
                                  QNode $1987 $1988 $1989 $1990 ->
                                    (QNode ((f1 $1967) $1987) ((f1 $1968) $1988) ((f1 $1969) $1989) ((f1 $1970) $1990));
                                };
                            }))
                      in
                        ((f1 $1126) $1166))
                      (letrec
                        g1=(\t->
                          (\x1->
                            case  t  of {
                              QError  -> QError;
                              QNone  ->
                                case  x1  of {
                                  QError  -> QError;
                                  QNone  -> QNone;
                                  QVal $1416 -> QNone;
                                  QNode $1417 $1418 $1419 $1420 -> QNone;
                                };
                              QVal $1401 ->
                                case  x1  of {
                                  QError  -> QError;
                                  QNone  -> QNone;
                                  QVal $1421 -> (QVal ((mlt $1401) $1421));
                                  QNode $1422 $1423 $1424 $1425 -> QError;
                                };
                              QNode $1407 $1408 $1409 $1410 ->
                                case  x1  of {
                                  QError  -> QError;
                                  QNone  -> QNone;
                                  QVal $1426 -> QError;
                                  QNode $1427 $1428 $1429 $1430 ->
                                    (QNode ((g1 $1407) $1427) ((g1 $1408) $1428) ((g1 $1409) $1429) ((g1 $1410) $1430));
                                };
                            }))
                      in
                        ((g1 $1127) $1167)));
                };
            };
          QVal $95 ->
            case  y  of {
              QError  -> QError;
              QNone  ->
                case  z  of {
                  QError  -> QError;
                  QNone  -> (QVal $95);
                  QVal $919 -> (QVal $95);
                  QNode $920 $921 $922 $923 -> (QVal $95);
                };
              QVal $894 ->
                case  z  of {
                  QError  -> QError;
                  QNone  -> (QVal $95);
                  QVal $929 -> (QVal ((pls $95) ((mlt $894) $929)));
                  QNode $930 $931 $932 $933 -> QError;
                };
              QNode $900 $901 $902 $903 ->
                case  z  of {
                  QError  -> QError;
                  QNone  -> (QVal $95);
                  QVal $939 -> QError;
                  QNode $940 $941 $942 $943 -> QError;
                };
            };
          QNode $101 $102 $103 $104 ->
            case  y  of {
              QError  -> QError;
              QNone  ->
                case  z  of {
                  QError  -> QError;
                  QNone  -> (QNode $101 $102 $103 $104);
                  QVal $259 -> (QNode $101 $102 $103 $104);
                  QNode $260 $261 $262 $263 -> (QNode $101 $102 $103 $104);
                };
              QVal $234 ->
                case  z  of {
                  QError  -> QError;
                  QNone  -> (QNode $101 $102 $103 $104);
                  QVal $269 -> QError;
                  QNode $270 $271 $272 $273 -> QError;
                };
              QNode $240 $241 $242 $243 ->
                case  z  of {
                  QError  -> QError;
                  QNone  -> (QNode $101 $102 $103 $104);
                  QVal $279 -> QError;
                  QNode $280 $281 $282 $283 ->
                    (QNode (((f $101) $240) $280) (((f $102) $241) $281) (((f $103) $242) $282) (((f $104) $243) $283));
                };
            };
        })))
in
  (((f m1) m2) m3))
